# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod Properties
mod_version = 1.0.3
maven_group = com.github.itzswirlz.slstoof
archives_name = soletssettheoreonfire
enabled_platforms = fabric,neoforge

minecraft_version=26.2

# Dependencies
architectury_api_version = 21.0.2
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2
neoforge_version = 26.2.0.1-beta

loom.ignoreDependencyLoomVersionValidation=true
loom.allowMismatchedPlatformVersion = true
fabric.loom.disableObfuscation=true
