modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/jpeisach/slstoof/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "soletssettheoreonfire"
version = "${version}"
displayName = "So Let's Set The Ore On Fire"
authors = "ItzSwirlz/jpeisach"
description = '''
Adds correct ore-specific fire colors and respective blocks, so they can burn brighter than the sun.
'''
logoFile = "icon.png"

[[dependencies.soletssettheoreonfire]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soletssettheoreonfire]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soletssettheoreonfire]]
modId = "architectury"
type = "required"
versionRange = "[20.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "soletssettheoreonfire.mixins.json"
